"""initial

Revision ID: 3044c64bd8b7
Revises: 
Create Date: 2015-04-29 08:54:03.261000

"""

# revision identifiers, used by Alembic.
revision = '3044c64bd8b7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sphinx_nodes')
    op.drop_table('sphinx_commentvote')
    op.drop_table('sphinx_comments')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sphinx_comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.INTEGER(), nullable=False),
    sa.Column('time', sa.DATETIME(), nullable=False),
    sa.Column('text', sa.TEXT(), nullable=False),
    sa.Column('displayed', sa.BOOLEAN(), nullable=True),
    sa.Column('username', sa.VARCHAR(length=64), nullable=True),
    sa.Column('proposal', sa.TEXT(), nullable=True),
    sa.Column('proposal_diff', sa.TEXT(), nullable=True),
    sa.Column('path', sa.VARCHAR(length=256), nullable=True),
    sa.Column('node_id', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], [u'sphinx_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sphinx_commentvote',
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('comment_id', sa.INTEGER(), nullable=False),
    sa.Column('value', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], [u'sphinx_comments.id'], ),
    sa.PrimaryKeyConstraint('username', 'comment_id')
    )
    op.create_table('sphinx_nodes',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('document', sa.VARCHAR(length=256), nullable=False),
    sa.Column('source', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
